name: Testes
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Rodar os testes
      run: python -m unittest testes_conta.py
